<a href="https://colab.research.google.com/github/danhhuit/deep_learning_practice/blob/main/Buoi01_NguyenThanhDanh_2001230095.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# khai bao thu vien
import numpy as np
from numpy._core.numeric import ones

import pandas as pd

# Numpy:

In [ ]:
# a. Tao mang 1 chieu:
single_list = [14, 7 , 2005, 6, 5 , 2026]
print('Danh sach cac phan tu:\n', single_list)

# list --> numpy arr
single_arr = np.array(single_list)
print('Mang 1 chieu cac phan tu:\n', single_arr)

# Cach khac:
single_arr2 = np.array([14, 7 , 2005, 6, 5 , 2026])
print('Mang 1 chieu cac phan tu:\n', single_arr2)

Danh sach cac phan tu:
 [14, 7, 2005, 6, 5, 2026]
Mang 1 chieu cac phan tu:
 [  14    7 2005    6    5 2026]
Mang 1 chieu cac phan tu:
 [  14    7 2005    6    5 2026]


In [ ]:
# b. Tao mang 2 chieu:
double_arr = np.array([
                        [1, 2, 3],
                        [4, 5, 6]
                      ])
print('Mang 2 chieu cac phan tu:\n', double_arr)
print('Kich thuoc mang:\n', double_arr.shape)
print('Kieu du lieu:\n', double_arr.dtype)

Mang 2 chieu cac phan tu:
 [[1 2 3]
 [4 5 6]]
Kich thuoc mang:
 (2, 3)
Kieu du lieu:
 int64


In [ ]:
# c. Tao mang 3 chieu:
triple_arr = np.array([
                        [[1, 2, 3],
                         [4, 5, 6]],
                        [['hi', 8, 9],
                         [10, 11, 12]]
                      ])
print('Mang 3 chieu cac phan tu:\n', triple_arr)
print('Kich thuoc mang: ', triple_arr.shape)
print('Kieu du lieu: ', triple_arr.dtype)

Mang 3 chieu cac phan tu:
 [[['1' '2' '3']
  ['4' '5' '6']]

 [['hi' '8' '9']
  ['10' '11' '12']]]
Kich thuoc mang:  (2, 2, 3)
Kieu du lieu:  <U21


In [ ]:
# d. Tao Array voi gia tri ban dau la 0 hoac 1
zeros_matrix = np.zeros((2, 3)) # n dong, m cot
print('Mang 0:\n', zeros_matrix)
print('Kich thuoc mang 0: ', zeros_matrix.shape)
print('Kieu du lieu mang 0: ', zeros_matrix.dtype)

ones_matrix = np.ones((2, 2))
print('Mang 1:\n', ones_matrix)
print('Kich thuoc mang 1: ', ones_matrix.shape)
print('Kieu du lieu mang 1: ', ones_matrix.dtype)

Mang 0:
 [[0. 0. 0.]
 [0. 0. 0.]]
Kich thuoc mang 0:  (2, 3)
Kieu du lieu mang 0:  float64
Mang 1:
 [[1. 1.]
 [1. 1.]]
Kich thuoc mang 1:  (2, 2)
Kieu du lieu mang 1:  float64


In [ ]:
# e. Reshape
matrix = np.array([[1.,2.,3.], [4.,5.,6.]])
print('Ma tran ban dau:\n', matrix)
print('Kich thuoc ma tran ban dau:\n', matrix.shape)

re_matrix = matrix.reshape((3, 2))
print('Ma tran sau khi reshape:\n', re_matrix)
print('Kich thuoc ma tran sau khi reshape:\n', re_matrix.shape)

matrix2 = np.array([
                      [[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]]
                    ])
print('Ma tran ban dau:\n', matrix2)
print('Kich thuoc ma tran ban dau:\n', matrix2.shape)

re_matrix2 = matrix2.reshape((3, 2, 2))
print('Ma tran sau khi reshape:\n', re_matrix2)

Ma tran ban dau:
 [[1. 2. 3.]
 [4. 5. 6.]]
Kich thuoc ma tran ban dau:
 (2, 3)
Ma tran sau khi reshape:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
Kich thuoc ma tran sau khi reshape:
 (3, 2)
Ma tran ban dau:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Kich thuoc ma tran ban dau:
 (2, 2, 3)
Ma tran sau khi reshape:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
# f. Flatten
matrix = np.array([[1., 2., 3.], [4., 5., 6.]])
fl_matrix = matrix.flatten()
print('Ma tran ban dau:\n', matrix)
print('Kich thuoc ma tran ban dau:\n', matrix.shape)
print('Ma tran sau khi chuyen ve 1 chieu:\n', fl_matrix)

matrix2 = np.array([[[1.,2.,3.],[4.,5.,6.]],[[7.,8.,9.], [10.,11.,12.]]])
print('Ma tran ban dau:\n', matrix2)
print('Kich thuoc ma tran ban dau:\n', matrix2.shape)
fl_matrix2 = matrix2.flatten()
print('Ma tran sau khi chuyen ve 1 chieu:\n', fl_matrix2)


Ma tran ban dau:
 [[1. 2. 3.]
 [4. 5. 6.]]
Kich thuoc ma tran ban dau:
 (2, 3)
Ma tran sau khi chuyen ve 1 chieu:
 [1. 2. 3. 4. 5. 6.]
Ma tran ban dau:
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
Kich thuoc ma tran ban dau:
 (2, 2, 3)
Ma tran sau khi chuyen ve 1 chieu:
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [ ]:
# g. hstack((x,y)) va vstack((x,y))
matrix1 = np.array([1.,2.,3.])
matrix2 = np.array([7.,8.,9.])
print('Ma tran 1:\n', matrix1)
print('Ma tran 2:\n', matrix2)
print('Ket qua hstack (Horizontal Append):\n', np.hstack((matrix1, matrix2)))
print('Ket qua vstack (Vertical Append):\n', np.vstack((matrix1, matrix2)))

Ma tran 1:
 [1. 2. 3.]
Ma tran 2:
 [7. 8. 9.]
Ket qua hstack (Horizontal Append):
 [1. 2. 3. 7. 8. 9.]
Ket qua vstack (Vertical Append):
 [[1. 2. 3.]
 [7. 8. 9.]]


In [ ]:
# h. Mang ngau nhien
rnd_single_matrix = np.random.randint(100, size=(5,))
print('Mang ngau nhien 1 chieu:\n', rnd_single_matrix)
print('Kieu du lieu: ', rnd_single_matrix.dtype)

rnd_double_matrix = np.random.randint(100, size=(2, 3))
print('Mang ngau nhien 2 chieu:\n', rnd_double_matrix)
print('Kieu du lieu: ', rnd_double_matrix.dtype)

rnd_triple_matrix = np.random.randint(100, size=(3, 5, 3))
print('Mang ngau nhien 3 chieu:\n', rnd_triple_matrix)
print('Kieu du lieu: ', rnd_triple_matrix.dtype)

Mang ngau nhien 1 chieu:
 [ 7 58 82 34 62]
Kieu du lieu:  int64
Mang ngau nhien 2 chieu:
 [[26 21 61]
 [98 81 84]]
Kieu du lieu:  int64
Mang ngau nhien 3 chieu:
 [[[19 46 23]
  [37 80 18]
  [26 71 37]
  [92  9 14]
  [32 17 83]]

 [[33 74 85]
  [79 22 36]
  [ 3 72 75]
  [ 7 14 69]
  [11 72 49]]

 [[92 48 90]
  [ 8 19 34]
  [17 26 34]
  [62 77 26]
  [28 66 94]]]
Kieu du lieu:  int64


In [ ]:
# i. Mang so thuc ngau nhien trong khoang [0, 1]
rnd_single_matrix = np.random.rand(5)
print('Mang ngau nhien 1 chieu:\n', rnd_single_matrix)
print('Kieu du lieu: ', rnd_single_matrix.dtype)

rnd_double_matrix = np.random.rand(2, 3)
print('Mang ngau nhien 2 chieu:\n', rnd_double_matrix)
print('Kieu du lieu: ', rnd_double_matrix.dtype)

rnd_triple_matrix = np.random.rand(3, 5, 3)
print('Mang ngau nhien 3 chieu:\n', rnd_triple_matrix)
print('Kieu du lieu: ', rnd_triple_matrix.dtype)

Mang ngau nhien 1 chieu:
 [0.33297933 0.2544879  0.59511475 0.20405284 0.39813238]
Kieu du lieu:  float64
Mang ngau nhien 2 chieu:
 [[0.19576157 0.74829121 0.38789352]
 [0.55313014 0.92994952 0.82696498]]
Kieu du lieu:  float64
Mang ngau nhien 3 chieu:
 [[[0.15523979 0.2185638  0.80532198]
  [0.58275408 0.08960926 0.60729365]
  [0.46318502 0.31101382 0.08192313]
  [0.63458605 0.12003785 0.85450936]
  [0.22936517 0.25437622 0.41916291]]

 [[0.32604885 0.75695049 0.21115056]
  [0.11442873 0.12695898 0.46123263]
  [0.95303516 0.00810413 0.9236175 ]
  [0.76148424 0.90194894 0.84568141]
  [0.53545083 0.9182608  0.92223431]]

 [[0.06579337 0.41822278 0.37303395]
  [0.87714179 0.02399339 0.0865113 ]
  [0.16607337 0.39209354 0.26080217]
  [0.12038068 0.34198823 0.42663719]
  [0.24565267 0.30023018 0.42513553]]]
Kieu du lieu:  float64


In [ ]:
# k. Mang so ngau nhien theo phan phoi chuan GAUSSIAN
# numpy.random.normal(loc, scale, size)
rnd_single_matrix = np.random.normal(0, 1, 5)
print('Mang ngau nhien 1 chieu:\n', rnd_single_matrix)
print('Kieu du lieu: ', rnd_single_matrix.dtype)

Mang ngau nhien 1 chieu:
 [ 0.25058524  0.32913809 -0.0897505   1.24317626  1.48466448]
Kieu du lieu:  float64


In [ ]:
# l. Sinh ngau nhien mot gia tri tu mang gia tri cho truoc
rnd_single_matrix = np.random.choice([3, 5, 7, 9])
print('Mang ngau nhien 1 chieu:\n', rnd_single_matrix)
print('Kieu du lieu: ', rnd_single_matrix.dtype)
# sinh ma tran 3x3 ngau nhien tu mang gia tri cho truoc
rnd_double_matrix = np.random.choice([3, 5, 7, 9], size=(3, 3))
print('Mang ngau nhien 2 chieu:\n', rnd_double_matrix)

Mang ngau nhien 1 chieu:
 7
Kieu du lieu:  int64
Mang ngau nhien 2 chieu:
 [[5 9 7]
 [5 5 3]
 [3 5 7]]


In [ ]:
# m. Thay doi gia tri cua ma tran
ones_matrix = np.matrix(np.ones((5, 5)))
print('Ma tran goc:\n', ones_matrix)

np.array(ones_matrix)[2] = 2
print('Thay doi gia tri dong thu 3 voi array:\n', ones_matrix)

np.asarray(ones_matrix)[2] = 2
print('Thay doi gia tri dong thu 3 voi asarray:\n', ones_matrix)

Ma tran goc:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Thay doi gia tri dong thu 3 voi array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Thay doi gia tri dong thu 3 voi asarray:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# n. Sinh day so theo khoang cho truoc
# Ham arrange:
arrange_list = np.arange(1, 20) # 1-> (n-1)
print('Day so tu 1 den 20:\n', arrange_matrix)

arrage_list = np.arange(1, 20, 2) # 1-> (n-1) co khoang cach 2
print('Day so tu 1 den 20 co khoang cach 2:\n', arrage_matrix2)

# Ham linspace:
lin_list = np.linspace(1.,2., num=5)
print('Day so linspace:\n', lin_list)

Day so tu 1 den 20:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Day so tu 1 den 20 co khoang cach 2:
 [ 1  3  5  7  9 11 13 15 17 19]
Day so linspace:
 [1.   1.25 1.5  1.75 2.  ]


In [ ]:
# o. index va slice
# quy tac index:
# - gia tri truoc dau ',' la so dong
# - gia tri sau dau ',' la so cot
# - muon chon mot dong hoac cot cu the thi can them dau ':'
# slice:
matrix = np.array([
                      [1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]
                    ])
print('Ma tran goc:\n', matrix)
print('Dong dau tien:\n', matrix[0])
print('Dong thu hai:\n', matrix[1])

# index:
print('Cot thu nhat:\n', matrix[:,0])
print('Cot thu hai:\n', matrix[:,1])
print('Phan tu dong thu 2 cot thu 2:\n', matrix[1,:2])


Ma tran goc:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dong dau tien:
 [1 2 3]
Dong thu hai:
 [4 5 6]
Cot thu nhat:
 [1 4 7]
Cot thu hai:
 [2 5 8]
Phan tu dong thu 2 cot thu 2:
 [4 5]


# Pandas

In [87]:
# a. Series:
series_list = pd.Series([1., 2., 3., 4.])
print('Series:\n', series_list)
print('Gia tri dau tien:\n', series_list[0])

series_list2 = pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])
print('Series:\n', series_list2)
print('Gia tri dau tien:\n', series_list2['a'])

# dictionary:
kilometers = {"day1": 420, "day2": 380, "day3": 390}
series_dict = pd.Series(kilometers)
print('Series:\n', series_dict)


Series:
 0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64
Gia tri dau tien:
 1.0
Series:
 a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64
Gia tri dau tien:
 1.0
Series:
 day1    420
day2    380
day3    390
dtype: int64


In [98]:
# b. Dataframe:
# numpy --> pandas
matrix = np.array([[1,2], [3, 4]])
df_matrix = pd.DataFrame(matrix)
print('Dataframe:\n', df_matrix)

# pandas --> numpy
numpy = np.array(df_matrix)
print('Numpy:\n', numpy)

dictionary = {'Name':['Nguyen', 'Danh'], 'Age':[30, 40]}
df_dictionary = pd.DataFrame(dictionary)
print('Dataframe:\n', df_dictionary)

# tao mang 40 x 10
rnd_matrix = np.random.randint(100, size=(40, 10))
df_rnd_matrix = pd.DataFrame(rnd_matrix, columns=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
# print(df_rnd_matrix.head())
# print(df_rnd_matrix.tail())

Dataframe:
    0  1
0  1  2
1  3  4
Numpy:
 [[1 2]
 [3 4]]
Dataframe:
      Name  Age
0  Nguyen   30
1    Danh   40


In [104]:
# c. Noi nhieu DataFrame
df1 = pd.DataFrame({'Name':['Nguyen','Thanh', 'Danh'],
                    'Age': [21, 33, 12]
                    }, index=[0,1,2])
df2 = pd.DataFrame({'Name':['Thanh', 'Danh'],
                    'Age': [26, 34]
                    }, index=[3, 4])
df_concat = pd.concat([df1, df2])
print('Noi chuoi 2 DataFrame:\n',df_concat)
# xoa cot ten trung nhau
print('Xoa gia tri cot ten trung nhau trong DataFrame:\n', df_concat.drop_duplicates(subset=['Name']))
# sap xep gia tri
print('Sap xep gia tri trong DataFrame:\n', df_concat.sort_values(by=['Age']))
# doi ten cot
df_rename = df_concat.rename(columns={'Name': 'Ho va ten', 'Age': 'Tuoi'})
print('Doi ten cot trong DataFrame:\n', df_rename)

Noi chuoi 2 DataFrame:
      Name  Age
0  Nguyen   21
1   Thanh   33
2    Danh   12
3   Thanh   26
4    Danh   34
Xoa gia tri cot ten trung nhau trong DataFrame:
      Name  Age
0  Nguyen   21
1   Thanh   33
2    Danh   12
Sap xep gia tri trong DataFrame:
      Name  Age
2    Danh   12
0  Nguyen   21
3   Thanh   26
1   Thanh   33
4    Danh   34
Doi ten cot trong DataFrame:
   Ho va ten  Tuoi
0    Nguyen    21
1     Thanh    33
2      Danh    12
3     Thanh    26
4      Danh    34


In [116]:
# d. Doc du lieu tu CSV
# pandas.read_csv(filepath_or_buffer, sep='','names=None', 'index_col=None', 'skipinitialspace=False')
path = 'https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/main/Data/dulieuxettuyendaihoc.csv'
COLUMNS = ['T1', 'S1', 'L1']
df_csv1 = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)
df_csv2 = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv2.head())
print(df_csv2.shape)

    T1   S1   L1
0  STT   T1   L1
1    1  7.2  7.3
2    2  5.4  3.9
3    3  5.6  6.8
4    4  6.6  6.4
(101, 3)
   STT   T1   L1   H1   S1   V1   X1   D1   N1   T2  ...   X6   D6   N6  GT  \
0    1  7.2  7.3  6.3  7.3  7.0  7.9  7.3  5.5  8.4  ...  6.6  7.6  5.9   F   
1    2  5.4  3.9  3.9  4.0  5.4  5.4  5.3  2.8  6.3  ...  6.6  6.1  4.4   M   
2    3  5.6  6.8  7.2  7.5  4.3  7.4  5.8  3.2  5.0  ...  7.9  8.1  4.6   M   
3    4  6.6  6.4  5.3  6.9  5.4  7.3  6.4  5.8  5.1  ...  7.1  7.3  7.4   M   
4    5  6.0  5.0  6.0  7.3  6.5  7.7  7.9  6.1  5.4  ...  6.1  7.5  7.2   M   

   DT   KV   DH1   DH2   DH3  KT  
0 NaN  2NT  3.25  3.25  4.50  A1  
1 NaN    1  6.00  4.00  3.50   C  
2 NaN    1  5.00  6.75  4.00   C  
3 NaN    1  4.25  4.25  5.25  D1  
4 NaN  2NT  4.25  4.50  5.00   A  

[5 rows x 56 columns]
(100, 56)


/tmp/ipykernel_2140/3929855393.py:5: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df_csv1 = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)


In [125]:
# e. Gom nhom du lieu DataFrame
# groupby()
path = 'https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/main/Data/dulieuxettuyendaihoc.csv'
df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv.head())
print(df_csv.groupby(['GT']).mean(numeric_only=True).head())
print(df_csv.groupby(['T1', 'L1']).min().head())
print(df_csv.groupby(['T1', 'L1'])['GT'].min().head())
# print(df_csv.groupby())
# df_groupby = df_csv.groupby('GT')
# print(df_groupby.groups)

   STT   T1   L1   H1   S1   V1   X1   D1   N1   T2  ...   X6   D6   N6  GT  \
0    1  7.2  7.3  6.3  7.3  7.0  7.9  7.3  5.5  8.4  ...  6.6  7.6  5.9   F   
1    2  5.4  3.9  3.9  4.0  5.4  5.4  5.3  2.8  6.3  ...  6.6  6.1  4.4   M   
2    3  5.6  6.8  7.2  7.5  4.3  7.4  5.8  3.2  5.0  ...  7.9  8.1  4.6   M   
3    4  6.6  6.4  5.3  6.9  5.4  7.3  6.4  5.8  5.1  ...  7.1  7.3  7.4   M   
4    5  6.0  5.0  6.0  7.3  6.5  7.7  7.9  6.1  5.4  ...  6.1  7.5  7.2   M   

   DT   KV   DH1   DH2   DH3  KT  
0 NaN  2NT  3.25  3.25  4.50  A1  
1 NaN    1  6.00  4.00  3.50   C  
2 NaN    1  5.00  6.75  4.00   C  
3 NaN    1  4.25  4.25  5.25  D1  
4 NaN  2NT  4.25  4.50  5.00   A  

[5 rows x 56 columns]
          STT        T1        L1        H1        S1        V1        X1  \
GT                                                                          
F   45.145833  6.187500  6.135417  6.472917  6.504167  6.331250  6.727083   
M   55.442308  5.723077  5.536538  6.100000  6.503846  5.5403